name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN_BD_HIERARCHY: ${{ secrets.HF_TOKEN_BD_HIERARCHY }}
        run: |
          git push --force https://Meshkat-Shadik:$HF_TOKEN_BD_HIERARCHY@huggingface.co/spaces/MeshkatShadik/bd-hierarchy-location-finder main